name: covid19fighter
description: Coronavirus 8bit Fighters

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # This package used to provide number formatting
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.3
  # Flutter Launcher Icons
  # Check the configurations below at "flutter_icons"
  # After setup the config file, run the below commands:
  # flutter pub run flutter_launcher_icons:main -f pubspec.yaml
  # flutter pub get
  # flutter pub run flutter_launcher_icons:main

  flutter_launcher_name: ^0.0.1
  # Flutter Launcher Name
  # Check the configurations below at "flutter_launcher_name"
  # After setup the config file, run the below command:
  # flutter pub run flutter_launcher_name:main

  flutter_native_splash: ^0.1.9
  # Flutter Native Splash
  # Check the configurations below at "flutter_native_splash"
  # After adding the settings, run the package using the below commands:
  # flutter pub pub run flutter_native_splash:create

# Flutter Launcher Icons Configurations
flutter_icons:
  android: true # android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon_adaptive_foreground.png"
  adaptive_icon_background: "#33ffcc"

# Flutter Launcher Name Configurations
flutter_launcher_name:
  name: "COVID-19 Fighters"

# Flutter Native Splash
flutter_native_splash:
  image: assets/splash/splash.png
  color: "#33ffcc"
  android_disable_fullscreen: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/graphics/graphics.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
